language: rust
cache: cargo
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    os: linux
  - env: TARGET=armv7-unknown-linux-gnueabihf
    os: linux
    addons:
      apt:
        packages:
        - libc6-i386
        - libc6-dev-i386
        - gcc-arm-linux-gnueabihf
        - libc6-armhf-cross
        - libc6-dev-armhf-cross
install:
- cargo fetch
- rustup target add armv7-unknown-linux-gnueabihf
- rustup component add rustfmt
script:
- cargo build && cargo test && cargo build --target=$TARGET --release
before_deploy:
- tar -cvf target/gps-util-$TARGET-$TRAVIS_TAG.tgz -C target/$TARGET/release/ gps-util
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: releases
  api_key:
    secure: iq1BL/Zs+Nfay3ZaRYJakTvLusf+L6x/5YQ+2/MzJULQPI6t6Fskfi+U2mf2iELd1SLrBPW/ujp2sBsBgQLPg0MDrbrSXqbBlzo3c12NB8f5QZTdhGEG6thoc3STA1fi67aQTXZQ+XfPyHDsbMYsoAgqWFYEfarBniBvNAp47eoVoxehjHHkmFPZop5tOHQhWznTXQM1ieEFxoPJrCIhwisNTtvFKTsHWgLxveAokVx7BpTfD01uybkM30gSi5uCy8ixo1L8VtiepEIdI3wwqlwsV3tKf1TOQSeh2xJMz2GJR75mqmPuVhIJ0dnG78AIh9S/G0JA4cze9EAz+Pdh67zuwe79WDlBVVeW2nDjmPLkyKaIsE6CF0HUQ0BLkOlX59I7DhB0m27IXmRTFv7eMnnnl/D7JePwDF8I6wgCGEtEtrGw+Aaku48V5BbhBed15Y735KBZxIuCDHgZj/98vEvxaZNg4kT1Wu8tpf2DNWsWNYe5jn7gNSIWgT56kByJ1Zdu1Whqw8aRiItdMcwpalg3wfN2NTGvED9BcJkM3lypqXPLHLDu/6JSTwCZtwH8/eVFltTJw8FdSBpw2T6YAjmixJ2sLVW2zJtat/KNecAavyX0/9ZpMhz0DP/maesDGRbFVMJcHT+uKBIn+Y1qZD8uN0PeEA8gRf3K9uTpa+o=
  file: target/*.tgz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: ryankurte/rust-embedded-gps

